name: Deploy pages

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3.8.1
              with:
                  node-version: "latest"
            - uses: actions/cache@v3
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              run: |
                  npm install
            - name: Build Slides
              run: |
                  npm run build -- --base /${{ github.event.repository.name }}/
                  cp dist/index.html dist/404.html
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v2
              with:
                  artifact_name: dist
